# 站点全局配置
baseURL = "https://example.org/"
defaultContentLanguage = "zh-cn"
locale = "zh-cn"
hasCJKLanguage = true
title = "Class Blog"
theme = "hugo-theme-stack"

# 分页
[pagination]
    pagerSize = 10

# 永久链接（短链接风格）
[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"

# Markdown 渲染 / 代码高亮 / 目录
[markup]
    [markup.goldmark]
        [markup.goldmark.extensions]
            [markup.goldmark.extensions.passthrough]
                enable = true
                [markup.goldmark.extensions.passthrough.delimiters]
                    block = [["\\[", "\\]"], ["$$", "$$"]]
                    inline = [["\\(", "\\)"]]
        [markup.goldmark.renderer]
            unsafe = true
    [markup.tableOfContents]
        endLevel = 4
        ordered = true
        startLevel = 2
    [markup.highlight]
        noClasses = false
        codeFences = true
        guessSyntax = true
        lineNoStart = 1
        lineNos = true
        lineNumbersInTable = true
        tabWidth = 4

# 主题参数
[params]
    mainSections = ["post"]
    rssFullContent = true

    [params.footer]
        since = 2026

    [params.sidebar]
        emoji = "📝"
        subtitle = "记录与分享"

    [params.article]
        [params.article.license]
            enabled = true
            default = "Licensed under [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)"

    [params.widgets]
        homepage = [
            { type = "search" },
            { type = "archives", params = { limit = 5 } },
            { type = "categories", params = { limit = 10 } },
            { type = "tag-cloud", params = { limit = 10 } },
        ]
        page = [{ type = "toc" }]

    [params.comments]
        enabled = false

    [params.cookies]
        enabled = false

# 侧边栏社交链接
[[menu.social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/mantoujun12"
    [menu.social.params]
        icon = "brand-github"
